#Co-Occurance Matrix

Shows how frequently words appear together in a corpus.

In [ ]:
import numpy as np
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer

In [ ]:
#Corpus
corpus= ["the cat sat on the mat","the dog sat on the log"]

In [ ]:
#Create a CountVectorizer to convert words to numbers
vectorizer=CountVectorizer()
x = vectorizer.fit_transform(corpus)

In [ ]:
#Convert to co-occurance matrix
co_occurance_matrix=(x.T*x)
#np.fill_diagonal(co_occurance_matrix.toarray(), 0)

In [ ]:
# Convert to Data Frame for better readability
co_occcurance_df=pd.DataFrame(co_occurance_matrix.toarray(),
                              index=vectorizer.get_feature_names_out(),
                              columns=vectorizer.get_feature_names_out())

In [ ]:
print("Co-occurance Matrix is : ")
print(co_occcurance_df)

Co-occurance Matrix is : 
     cat  dog  log  mat  on  sat  the
cat    1    0    0    1   1    1    2
dog    0    1    1    0   1    1    2
log    0    1    1    0   1    1    2
mat    1    0    0    1   1    1    2
on     1    1    1    1   2    2    4
sat    1    1    1    1   2    2    4
the    2    2    2    2   4    4    8


In [ ]:
vectorizer.get_feature_names_out()

array(['cat', 'dog', 'log', 'mat', 'on', 'sat', 'the'], dtype=object)

#Cosine Similarity

Measures the cosine of the angle between two word vectors in a vector space.

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity

In [ ]:
# Example word vectors (from a hypothetical embedding)
word_vectors= {
    "cat" : [1,0,0,0],
    "dog" : [0,1,0,0],
    "mat" : [0,0,1,0],
    "log" : [0,0,0,1]
}

In [ ]:
# Convert to a matrix
import numpy as np
vectors=np.array(list(word_vectors.values()))
vectors

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [ ]:
# Compute cosine similarity
cos_sim=cosine_similarity(vectors)

In [ ]:
print(cos_sim)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
# convert to Data Frame
cos_sim_df=pd.DataFrame(cos_sim,index=word_vectors.keys(),columns=word_vectors.keys())
print("\nCosine Similarity Matrix = ")
print(cos_sim_df)


Cosine Similarity Matrix = 
     cat  dog  mat  log
cat  1.0  0.0  0.0  0.0
dog  0.0  1.0  0.0  0.0
mat  0.0  0.0  1.0  0.0
log  0.0  0.0  0.0  1.0
